# Generated by Django 6.0 on 2026-01-04 01:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_FILA', 'Em fila'), ('EM_PROJETO', 'Em projeto'), ('AGUARDANDO_APROVACAO', 'Aguardando aprovação'), ('RETRABALHO', 'Retrabalho'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], db_index=True, default='EM_FILA', max_length=30)),
                ('prioridade', models.IntegerField(choices=[(1, 'Baixa'), (2, 'Média'), (3, 'Alta'), (4, 'Crítica')], default=2)),
                ('criado_em', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atribuido_para', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_atribuidas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_de', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_FILA', 'Em fila'), ('EM_PROJETO', 'Em projeto'), ('AGUARDANDO_APROVACAO', 'Aguardando aprovação'), ('RETRABALHO', 'Retrabalho'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], max_length=30)),
                ('status_para', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_FILA', 'Em fila'), ('EM_PROJETO', 'Em projeto'), ('AGUARDANDO_APROVACAO', 'Aguardando aprovação'), ('RETRABALHO', 'Retrabalho'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], max_length=30)),
                ('comentario', models.CharField(blank=True, max_length=300)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('alterado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='portal.solicitacao')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
