# Generated by Django 6.0 on 2026-01-04 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacao",
            name="secao",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="job",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="jobs_envolvidas",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="descricao_ferramenta",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="desenho_referencia",
            field=models.FileField(blank=True, null=True, upload_to="solicitacoes/referencias/"),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="wc",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="quantidade",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="solicitado_em",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="evento_sap",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="observacoes_projeto",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="numero_moc",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="area",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="baseline_ame",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="baseline_producao",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="tipo_identificacao",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="linha_produto",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="descricao_tecnica",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="material",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="tratamento",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="dim_criticas",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="anexos",
            field=models.FileField(blank=True, null=True, upload_to="solicitacoes/anexos/"),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="prazo_estimado",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="observacoes_aprovacao",
            field=models.TextField(blank=True),
        ),
    ]
