# Generated by Django 6.0 on 2026-01-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_add_solicitacao_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacao",
            name="sufixo",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="numero_dispositivo",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
